---

version: '2.1'

services:
  weather:
    build:
      args:
      - buildno=1
      context: .
      dockerfile: Dockerfile
    container_name: weather
    domainname: local
    expose:
    - 80/tcp
    - 443/tcp
    healthcheck:
      interval: 5m
      retries: 5
      test:
      - CMD-SHELL
      - /usr/local/bin/docker-nginx-healthcheck
      timeout: 1m
    hostname: weather
    image: weather-nginx:v2
    ports:
    - 80:80/tcp
    - 443:443/tcp
    restart: always
    volumes:
    - ./volumes/nginx-website/conf.d:/etc/nginx/conf.d:rw
    - ./volumes/nginx-website/html:/usr/share/nginx/html:rw
    - ./volumes/nginx-website/nginx.conf:/etc/nginx/nginx.conf:ro
