---

version: "3"

services:
  weather:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather
    domainname: local
    healthcheck:
      interval: 5m
      retries: 5
      test:
      - CMD-SHELL
      - /usr/local/bin/docker-nginx-healthcheck
      timeout: 1m
    hostname: weather
    image: weather-nginx:v3
    ports:
    - "80"
    restart: always
    volumes:
    - ./volumes/nginx-website/conf.d:/etc/nginx/conf.d:rw
    - ./volumes/nginx-website/html:/usr/share/nginx/html:rw
    - ./volumes/nginx-website/nginx.conf:/etc/nginx/nginx.conf:ro
